.TH POMODORO_CURSES 1

.SH NAME
pomodoro_curses \- an ncurses Pomodoro timer

.SH SYNOPSIS
.B pomodoro_curses
[\fIOPTION\fR...]

.SH DESCRIPTION
\fBpomodoro_curses\fR is an ncurses-based Pomodoro timer that supports
arbitrarily long work and rest sessions.
.PP
\fBNOTE\fR: all duration-related arguments MUST be given in minutes.
.SH OPTIONS
.TP
.BR \-b " " \fIshort_break\fR
Specify the length of breaks between work sessions in the same set.
Default is 5.
.TP
.BR \-h
Show help message and exit.
.TP
.BR \-n " " \fInum_sets\fR
Specify the number of sets to do.
Default is 1.
.TP
.BR \-p " " \fIsessions_per_set\fR
Specify the number of work sessions in a set.
Default is 3.
.TP
.BR \-s " " \fIsession_length\fR
Specify the length of a single work session.
Default is 25.
.TP
.BR \-B " " \fIlong_break\fR
Specify the length of a long break between sets.
Default is 30.
